modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="da_weed_mod"
version="1.0.0"
displayName="Da Weed Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ndava, MCreator"

[[dependencies.da_weed_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




